services:
  db:
    image: mysql:8.3.0
    container_name: mysql_test
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      TZ: "Asia/Tokyo"

volumes:
  db-data: